/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pumpkin.glb --transform --keepmeshes --keepmaterials --format --shadows 
Files: pumpkin.glb [129.59MB] > C:\Users\janllyod09\Desktop\pumpkin-transformed.glb [3.5MB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pumpkin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Character1_LeftUpLeg} />
      <primitive object={nodes.Character1_RightUpLeg} />
      <primitive object={nodes.Character1_Spine} />
      <skinnedMesh geometry={nodes.body.geometry} material={materials.matBody} skeleton={nodes.body.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.cloth1.geometry} material={materials.matCloth} skeleton={nodes.cloth1.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.cloth2.geometry} material={materials.matCloth} skeleton={nodes.cloth2.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.cloth3.geometry} material={materials.matCloth} skeleton={nodes.cloth3.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.desna.geometry} material={materials.matHead} skeleton={nodes.desna.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.eyas.geometry} material={materials.matHead} skeleton={nodes.eyas.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.hat.geometry} material={materials.matHead} skeleton={nodes.hat.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.otrostki.geometry} material={materials.matBody} skeleton={nodes.otrostki.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.pipka.geometry} material={materials.matHead} skeleton={nodes.pipka.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.pumpkinHead.geometry} material={materials.matHead} skeleton={nodes.pumpkinHead.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.tooth1.geometry} material={materials.matHead} skeleton={nodes.tooth1.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.tooth2.geometry} material={materials.matHead} skeleton={nodes.tooth2.skeleton} position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/pumpkin-transformed.glb')
